Repository intel/terraform-intel-gcp-vm, pull requests merged in 2024-10, with the labels that each got.

#45 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#46 fix variable information
  examples/gcp-linux-tdx-vm/main.tf
  examples/gcp-linux-vm/variables.tf
  main.tf
Labels: enhancement, Review effort [1-5]: 2, bug fix

#47 Updated multiple examples and validated updates
  examples/gcp-linux-vm-ico-by-densify/README.md
  examples/gcp-linux-vm-ico-by-densify/densify_recommendations.auto.tfvars
  examples/gcp-linux-vm-ico-by-densify/variables.tf
  examples/gcp-rhel-vm/versions.tf
  examples/gcp-windows-vm-ico-by-densify/README.md
  examples/gcp-windows-vm-ico-by-densify/densify_recommendations.auto.tfvars
  examples/gcp-windows-vm-ico-by-densify/variables.tf
  examples/gcp-windows-vm/versions.tf
Labels: enhancement, Review effort [1-5]: 2

#50 Gcp linux vm spot update
  examples/gcp-linux-vm-spot/main.tf
  examples/gcp-linux-vm-spot/versions.tf
Labels: enhancement, Review effort [1-5]: 2, configuration changes
